language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  matrix:
    - DEBUG=1

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: DEBUG=0

    - php: 7.0
      env: DEBUG=0

before_script:
  - if [[ "$DEBUG" == "0" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - composer update-all
  - composer test

after_script:
  - if [[ "$DEBUG" == "1" ]]; then travis_retry composer coveralls; fi
