language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: config-rm xdebug.ini

    - php: 7.0
      env: config-rm xdebug.ini

script:
  - composer update-all
  - composer test

after_script:
  - composer coveralls
