language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

  include:
    - php: 5.6
      env: NODEBUG=1

    - php: 7.0
      env: NODEBUG=1

before_script:
  - if [[ "$NODEBUG" == "1" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - composer update-all
  - composer test

after_script:
  - composer coveralls
